In [14]:
import pandas as pd

In [15]:
df=pd.read_csv("ecommerce_sales_data.csv")
print("Shape:",df.shape)

Shape: (3500, 7)

In [16]:
print("\nColumns:",df.columns)

Columns: Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='object')

In [17]:
print("\nData Types:\n",df.dtypes)
print("\nMissing Values:\n",df.isnull().sum())

Data Types:
 Order Date       object
Product Name     object
Category         object
Region           object
Quantity          int64
Sales             int64
Profit          float64
dtype: object

Missing Values:
 Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

In [20]:
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [24]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df.dtypes

Order Date      datetime64[ns]
Product Name            object
Category                object
Region                  object
Quantity                 int64
Sales                    int64
Profit                 float64
dtype: object

In [28]:
df["Year"]=df["Order Date"].dt.year
df["Month"]=df["Order Date"].dt.month
df["Month Name"]=df["Order Date"].dt.month_name()

df.head()

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month,Month Name
0,2024-12-31,Printer,Office,North,4,3640,348.93,2024,12,December
1,2022-11-27,Mouse,Accessories,East,7,1197,106.53,2022,11,November
2,2022-05-11,Tablet,Electronics,South,5,5865,502.73,2022,5,May
3,2024-03-16,Mouse,Accessories,South,2,786,202.87,2024,3,March
4,2022-09-10,Mouse,Accessories,West,1,509,103.28,2022,9,September

In [29]:
df[df["Profit"]<0].head()

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit, Year, Month, Month Name]
Index: []

In [30]:
print("Minimum Profit:", df["Profit"].min())

Minimum Profit: 6.97

In [31]:
total_sales =df["Sales"].sum()
total_profit = df["Profit"].sum()

In [34]:
profit_margin=(total_profit/total_sales)*100
print("Overall Profit Margin: {:.2f}%".format(profit_margin))

Overall Profit Margin: 17.29%